### ISSUE TITLE
Change 'best practice' to 'recommendations'

### ISSUE THREAD

**Issue by pbuttigieg** [ESIPFed/bds-primer-best-practices#26]
**What section of the best practices does your suggestion relate to?**

The title and concept of what this work is.

**Short description of content that should be revised**

When something is called a **best** practice, the implication is that there is some evidence that it consistently delivers better results than some other practices. 

This isn't the case here - this document is more a set of recommendations that this cluster has reached a consensus on (which is of course valuable )

**Suggested revision**

Change all mentions of "best practice" to something like "recommendations" and make the provenance of these very clear .

**Comment by sformel-usgs** [comment]
Thanks @pbuttigieg .  I understand this reasoning, and I don't have strong feelings about it.  If others agree that it should change, then I suggest "recommended practices" instead of "recommendations".  It has a more actionable flavor to me, than recommendations on its own.  But I won't lose sleep over it :-)

**Comment by albenson-usgs** [comment]
I'm not in favor of "recommendations" as aside from the one section we just worked on, I don't think the primer really provides recommendations. Just highlights standards that exist for particular needs for biological observation data. I was just updating the ESIP BDS Cluster Wiki and we have referred to them previously as "companion products to the primer". I would be more comfortable just calling them primer companion products.

**Comment by pbuttigieg** [comment]
Why not simply illustrative examples? "Companion products" suggests that these entities are ancillary to the primer, and produced through a similar process, both of which are somewhat misleading

**Comment by albenson-usgs** [comment]
But they are ancillary to the primer and they so far the first one has been produced through a similar process and they don't provide any examples- just further information.

**Comment by sformel-usgs** [comment]
I think this is shaping up to be something that we should formally poll the cluster about. @timvdstap weigh in here too, I remember you had a thought about this, but I can't remember what it was.

This publication will have to get reviewed by the USGS for mine and Abby's sake and we need to be careful about words like "best" for that reason too.  But I'm concerned that we're headed in a direction of toothlessness.  In the spirit of trying to be ear/eye-catching, I suggest the "primer lagniappes" (lan-nyaps).  It's a New Orleans word for "a little something extra," and a word I dearly love.  It won't be intuitive to many users, but neither will it be dull.  I'll fight hard for lagniappe, but some other suggestions I've come up with include:

primer brass tacks
primer deets
primer obiter dictums
primer concessions
primer FWIWs

**Comment by timvdstap** [comment]
I agree that the word **best** might sound too 'strong'/off-putting for users to contribute to, and there's not really any metric to rank practices. Simply removing the word 'best' would perhaps make it toothless as Steve suggested. A poll might be a good to put forward to the group, if we can come up with some viable alternatives.

Perhaps BDS Primer good practices? Primer guidelines? Primer Ps & Qs? I'd feel better about good vs. best, in the sense that I feel like I can justify the practices being 'good' we advocate for adoption of international standards. Eh this reminds me I'm horrible at semantics!

**Comment by sformel-usgs** [comment]
After thinking about this a little more, I think my favorite is a variation on @timvdstap's suggestion: the "ESIP BDS Primer Guide." Or: "The Guide to the ESIP BDS Primer." IMO, it sounds like an explanatory companion to the primer, but is a little more focused than companion, ancillary and recommendations.  It also feels like plain, friendly language that is neither too strong nor too weak, although that's just my subjectivity.  

I'd like to put this one out there for a vote at our next meeting, along with the other suggestions above.  @pbuttigieg since you started this issue, I'd like to check in with you.  Do you think it's ready for voting, or does it deserve more discussion?

**Comment by pbuttigieg** [comment]
@sformel-usgs I think there are good options listed. Reading those, and recalling

 "The best practice documents are intended to be a bridge between the full, lengthy standards documentation, and the short primer quick reference."

Perhaps we can add one or more of:

- Extensions to the ESIP Biological Data Standards Primer
- Appendices to the ESIP Biological Data Standards Primer
- Elaborations on the ESIP Biological Data Standards Primer
- Supplements to the ESIP Biological Data Standards Primer

**Comment by albenson-usgs** [comment]
Results from the Slido today- we settled on "Guidelines"
![slido-what-should-we-call-the-products-we-have-been-working-on-in-conjunction-with-the-primer](https://github.com/ESIPFed/bds-primer-best-practices/assets/7586150/fb0ad9c1-bf8e-4613-b5b9-b8051d6ad5b4) which Megan Carter noted during the call is also good because it's in line with what other clusters have done.
